name: Deploy to AWS ECR

on:
  push:
    branches:
      - main  # Change this to match your main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t dogwalker .

      # Tag Docker image
      - name: Tag Docker Image
        run: |
          docker tag dogwalker:latest 820242923371.dkr.ecr.us-east-1.amazonaws.com/dogwalker/api

      # Push Docker image to ECR
      - name: Push Docker Image to ECR
        run: |
          docker push 820242923371.dkr.ecr.us-east-1.amazonaws.com/dogwalker/api:latest